Projeto Lunary/Controllers/CampanhaController.cs
using Projeto_Lunary.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto_Lunary.Controllers
{
    public class CampanhaController : Controller
    {
        // GET: Campanha
        LunaryEntities1 bd = new LunaryEntities1();
        public ActionResult Index()
        {
            return View(bd.Campanhas.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string Descricao, float CAMPRECO, HttpPostedFileBase Foto)
        {
            Campanhas novacampanha = new Campanhas();
            novacampanha.CAMDESCRICAO = Descricao;
            novacampanha.CAMPRECO = CAMPRECO;
            if (Foto != null)
            {
                try
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        Foto.InputStream.CopyTo(memoryStream);
                        novacampanha.CAMFOTO = memoryStream.ToArray();
                    }
                }
                catch (Exception)
                {
                    return RedirectToAction("caixinha.js");
                }
                
            }
            
            bd.Campanhas.Add(novacampanha);
            bd.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Editar(int? id)
        {
            Campanhas Localizarcampanha = bd.Campanhas.ToList().Where(x => x.CAMID == id).First();
            return View(Localizarcampanha);
        }

        [HttpPost]
        public ActionResult Editar(int? id, string Descricao, float preco, HttpPostedFileBase Foto)
        {
            Campanhas atualizarcampanhas = bd.Campanhas.ToList().Where(x => x.CAMID == id).First();
            atualizarcampanhas.CAMDESCRICAO = Descricao;
            atualizarcampanhas.CAMPRECO = preco;
            if (Foto != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    Foto.InputStream.CopyTo(memoryStream);
                    atualizarcampanhas.CAMFOTO = memoryStream.ToArray();
                }
            }
            bd.Entry(atualizarcampanhas).State = EntityState.Modified;
            bd.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Excluir(int? id)
        {

            if (id != null)
            {
                try
                {
                    Campanhas excluir = bd.Campanhas.ToList().Where(x => x.CAMID == id).First();
                    return View(excluir);
                }
                catch (Exception)
                {
                    return View("ListPratos");
                }
            }
            return View("ListPratos");
        }
        [HttpPost]
        public ActionResult ExcluirConfirma(int? id)
        {
            if (id != null)
            {
                try
                {
                    Campanhas excluircampanha = bd.Campanhas.ToList().Where(x => x.CAMID == id).First();
                    bd.Campanhas.Remove(excluircampanha);
                    bd.SaveChanges();
                }
                catch (Exception)
                {
                    return RedirectToAction("index");
                }
            }
            return RedirectToAction("index");
        }

    }
}

Projeto Lunary/Controllers/ContaController.cs
using Projeto_Lunary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projeto_Lunary.Controllers
{
    public class ContaController : Controller
    {
        LunaryEntities1 bd = new LunaryEntities1();

        [AllowAnonymous]
        
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            var achou = (login.Usuario == "admin" && login.Senha == "123");

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Admin");
                    }
         
            }
            else
            {
                ModelState.AddModelError("", "Login inválido.");
            }

            return View(login);
        }
        
        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Admin");
        }


    }
}

Projeto Lunary/Controllers/QrCodeController.cs
using Projeto_Lunary.Models;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto_Lunary.Controllers
{
    [Authorize]
    public class QrCodeController : Controller
    {
        // GET: QrCode

        LunaryEntities1 bd = new LunaryEntities1();
        public ActionResult QR()
        {
            return View();
        }

        [HttpPost]
        public ActionResult QR (string qrcode)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                qrcode = Request.Url.Authority +  "/Restaurante/Menu";
                QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();
                QRCodeData qrCodeData = qRCodeGenerator.CreateQrCode(qrcode, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCode(qrCodeData);

                using (Bitmap bitmap = qrCode.GetGraphic(20))
                {
                    bitmap.Save(ms, ImageFormat.Png);
                    ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
        }

    }
}

Projeto Lunary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css" />

    <title>@ViewBag.Title - Lunary</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (Request.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="containerdiv">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Lunary", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="navbar-collapse collapse">
                    @using (Html.BeginForm("QR", "QrCode", FormMethod.Post, new { id = "QrCoder" }))
                    {
                        <ul class="nav navbar-nav navbar-left">
                            <li>&nbsp;&nbsp;&nbsp;</li>
                            <li>&nbsp;&nbsp;&nbsp;</li>
                            <li>@Html.ActionLink("Inicio", "Index", "Admin")</li>
                            <li>@Html.ActionLink("Lista dos Pratos", "ListPratos", "Admin")</li>
                            <li>@Html.ActionLink("Adicionar Pratos", "Create", "Admin")</li>
                            <li><a href="/Restaurante/Menu/" target="_blank">Menu Virtual</a></li>

                            <li>
                                <a href="javascript:document.getElementById('QrCoder').submit()">Qrcode</a>
                            </li>
                            
                            <li>@Html.ActionLink("Campanhas", "Index", "Campanha")</li>
                            <li>@Html.ActionLink("Produtos Mais Curtidos", "ProdutosCurtidos", "Admin")</li>
                        </ul>
                    }
                        @using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "LogOff" }))
                        {
                            <ul class="nav navbar-nav navbar-right">

                                <li><a href="#">Olá @User.Identity.Name</a></li>

                                <li><a href="javascript:document.getElementById('LogOff').submit()">Sair</a></li>
                                <li>&nbsp;&nbsp;&nbsp;</li>
                                <li>&nbsp;&nbsp;&nbsp;</li>
                            </ul>
                        }
                    </div>
            </div>

        </div>
    }

        <div class="container body-content">
            @RenderBody()
            <hr style="border-top: 1px solid #eeeeee00 " />
            
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>