Projeto Lunary/Controllers/AdiministradorController.cs
using Projeto_Lunary.Models;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto_Lunary.Controllers
{
    public class AdiministradorController : Controller
    {
        LunaryEntities bd = new LunaryEntities();

        public ActionResult Index()
        {
            ViewBag.ListCategorias = bd.Categorias.ToList();
            return View(bd.Restaurante.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.listacategoria = bd.Categorias.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(string nome, float preco, string descricao, float precopromocao, string categoria, HttpPostedFileBase imagem)
        {
            Restaurante novoRestaurante = new Restaurante();
            novoRestaurante.RESTANOME = nome;
            novoRestaurante.RESTAPRECO = preco;
            novoRestaurante.RESTADESCRICAO = descricao;
            novoRestaurante.RESTAPREPROMOCAO = precopromocao;
            novoRestaurante.RESTACATEGORIA = categoria;
            using (var memoryStream = new MemoryStream())
            {
                imagem.InputStream.CopyTo(memoryStream);
                novoRestaurante.imagem = memoryStream.ToArray();
            }
            bd.Restaurante.Add(novoRestaurante);
            bd.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Editar(int? id)
        {
            Restaurante Localizarrestaurante = bd.Restaurante.ToList().Where(x => x.RESTAUID == id).First();
            ViewBag.listacategoria = bd.Categorias.ToList();
            return View(Localizarrestaurante);
        }

        [HttpPost]
       
        public ActionResult Editar(int? id, string nome, float preco, string descricao, float precopromocao, string categoria, HttpPostedFileBase imagem)
        {
            Restaurante atualizarrestaurante = bd.Restaurante.ToList().Where(x => x.RESTAUID == id).First();
            atualizarrestaurante.RESTANOME = nome;
            atualizarrestaurante.RESTAPRECO = preco;
            atualizarrestaurante.RESTADESCRICAO = descricao;
            atualizarrestaurante.RESTAPREPROMOCAO = precopromocao;
            atualizarrestaurante.RESTACATEGORIA = categoria;
            using (var memoryStream = new MemoryStream())
            {
                imagem.InputStream.CopyTo(memoryStream);
                atualizarrestaurante.imagem = memoryStream.ToArray();
            }

            bd.Entry(atualizarrestaurante).State = EntityState.Modified;
            bd.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult Excluir(int? id)
        {
            Restaurante excluiroproduto = bd.Restaurante.ToList().Where(x => x.RESTAUID == id).First();
            return RedirectToAction("index");
        }
        [HttpPost]
        public ActionResult ExcluirConfirma(int? id)
        {
            Restaurante excluiroproduto = bd.Restaurante.ToList().Where(x => x.RESTAUID == id).First();
            bd.Restaurante.Remove(excluiroproduto);
            try
            {
                bd.SaveChanges();
            }
            catch (Exception)
            {
                return RedirectToAction("index");
            }
            return RedirectToAction("index");
        }

        public ActionResult QRCODindex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult QRCODindex(string qrcode)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();
                QRCodeData qrCodeData = qRCodeGenerator.CreateQrCode(qrcode, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCode(qrCodeData);

                using (Bitmap bitmap = qrCode.GetGraphic(20))
                {
                    bitmap.Save(ms, ImageFormat.Png);
                    ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();
        }
    }
}

Projeto Lunary/Views/Adiministrador/Create.cshtml
@model Projeto_Lunary.Models.Restaurante

@{
    ViewBag.Title = "Create";
}

<h2>Cadastro de Produto</h2>
<div>

    <form action="/Adiministrador/Create" enctype="multipart/form-data" method="post">

        <div class="form-group">
            <label for="nome">Nome Do Prato</label>
            <input type="text" class="form-control"
                   maxlength="100"
                   id="nome" name="nome"
                   required />
        </div>
        <div class="form-group">
            <label for="preco">Preço</label>
            <input type="text" class="form-control" step="0.010"
                   id="preco" name="preco"
                   required />
        </div>
        <div class="form-group">
            <label for="descricao">Descrição</label>
            <input type="text" class="form-control"
                   id="descricao" name="descricao">
        </div>
        <div class="form-group">
            <label for="precopromocao">Preço Promoção</label>
            <input type="text" class="form-control" value="0" step="0.010"
                   id="precopromocao" name="precopromocao" />
        </div>

        <div class="form-group">
            <select id="categoria" name="categoria">
                @foreach (var item in ViewBag.listacategoria)
                {
                    <option>@item.RESTACATEGORIA</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label for="imagem">Imagem</label>
            <input type="file" class="form-control"
                   id="imagem" name="imagem">
        </div>

        <div>
            <a href="/ADM/Index"><button type="button" class="btn btn-primary">Voltar</button>  </a>
            <a href="/ADM/Index"><button type="submit" class="btn btn-success">Salvar</button>  </a>
        </div>
    </form>
</div>

Projeto Lunary/Views/Adiministrador/Editar.cshtml
@model Projeto_Lunary.Models.Restaurante
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div>
    <form action="/Adiministrador/Editar?id=@Model.RESTAUID" enctype="multipart/form-data" method="post">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" maxlength="100" id="nome" name="nome" value="@Model.RESTANOME" required />
        <div>
            <label for="preco">Preço</label>
            <input type="text" class="form-control" id="" name="preco" value=@Model.RESTAPRECO required />
        </div>
        <div>
            <label for="descricao">Descrição</label>
            <input type="text" class="form-control" id="" name="descricao" value="@Model.RESTADESCRICAO">
        </div>
        <div>
            <label for="precopromocional">Preço Promocional</label>
            <input type="text" class="form-control" id="" name="precopromocional" value=@Model.RESTAPREPROMOCAO>
        </div>
        <div>
            <br />
            <label for="categoria">Categoria: </label>
            <select id="categoria" name="categoria">
                @foreach (var item in ViewBag.listacategoria)
                {
                    <option>@item.RESTACATEGORIA</option>
                }
            </select>
        </div>

        <div>
            <label for="imagem"></label>
            <input type="file" class="form-control" id="imagem" name="imagem" value=@Model.imagem>
            <td>
                @{
                    if (Model.imagem != null)
                    {
                        var base64 = Convert.ToBase64String(Model.imagem);
                        var imgSrc = String.Format("data:image/jpg/gif/png;base64,{0}", base64);
                        <img src='@imgSrc' style="max-width:100px; max-height:100px;" />
                    }
                }
            </td>
        </div>
        <br />
        <div>
            <a href="/Adiministrador/Index"> <button type="button" class="btn btn-primary">Voltar</button>  </a>
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>

    </form>

</div>

Projeto Lunary/Views/Adiministrador/Excluir.cshtml
@model Projeto_Lunary.Models.Restaurante
@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<div>
    <form action="/Adiministrador/ExcluirConfirma?id=@Model.RESTAUID" enctype="multipart/form-data" method="post">
        <label>Prato: </label>
        <label>@Model.RESTANOME</label>

        <div>
            <label>Preço: </label>
            <label>@Model.RESTAPRECO</label>

        </div>

        <div>
            <label>Descrição: </label>
            <label>@Model.RESTADESCRICAO</label>

        </div>

        <div>
            <label>Preço Promocional: </label>
            <label>R$@Model.RESTAPREPROMOCAO</label>
        </div>

        <div>
            <label>Categoria: </label>
            <label>@Model.RESTACATEGORIA</label>
        </div>

        <div>
            <label>Categoria: </label>
            <label>@Model.imagem</label>
            <td>
                @{
                    if (Model.imagem != null)
                    {
                        var base64 = Convert.ToBase64String(Model.imagem);
                        var imgSrc = String.Format("data:image/jpg/gif/png;base64,{0}", base64);
                        <img src='@imgSrc' style="max-width:100px; max-height:100px;" />
                    }
                }
            </td>
        </div>

        <div>
            <a href="/Adiministrador/Index"><button type="button" class="btn btn-primary">Voltar</button></a>
            <a href="/Adiministrador/Index"><button type="submit" class="btn btn-danger">Excluir</button> </a>
        </div>

    </form>
</div>

Projeto Lunary/Views/Adiministrador/QRCODindex.cshtml
<link href="~/Content/QRCODE.css" rel="stylesheet" />
@{
    ViewBag.Title = "QRCODindex";
    Layout = null;
}

@using (Html.BeginForm("QRCODindex", "Adiministrador", FormMethod.Post))
{
    <div class="container">
        <input type="text" name="qrcode" />
        <br />
        <br />
        <div class="QRCode">
            <input type="submit" value="Generate" />
        </div>

        @if (ViewBag.QrCodeImage != null)
        {
            <img src="@ViewBag.QrCodeImage" alt="" style="height:300px;width:300px" />
        }
    </div>
}

Projeto Lunary/Views/Adiministrador/index.cshtml
<link href="~/Content/Site.css" rel="stylesheet" />
@model IEnumerable<Projeto_Lunary.Models.Restaurante>
@{
    ViewBag.Title = "Pratos";

}

<h2>Pratos</h2>

<thead>
    <h1>Lunary</h1>
    <p>Cardápio</p>
</thead>


<table class="table">
    <thead>
        <tr>
            <td class="text-center">Id</td>
            <td class="text-center">Prato</td>
            <td class="text-center">Preço</td>
            <td class="text-center">Descrição</td>
            <td class="text-center">Preço Promoção</td>         
            <td class="text-center">Categoria</td>
            <td></td>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">@item.RESTAUID</td>
                <td class="text-center">@item.RESTANOME</td>
                <td class="text-center">R$@item.RESTAPRECO</td>
                <td class="text-center">@item.RESTADESCRICAO</td>
                @if (@item.RESTAPREPROMOCAO != null)
                {
                    <td>
                        R$ @item.RESTAPREPROMOCAO
                    </td>
                }
                else
                {
                    <td> </td>
                }
                <td>@item.RESTACATEGORIA</td>
                <td>
                    @item.imagem
                    @{
                        if (item.imagem != null)
                        {
                            var base64 = Convert.ToBase64String(item.imagem);
                            var imgSrc = String.Format("data:image/jpg/gif/png;base64,{0}", base64);
                            <img src='@imgSrc' style="max-width:300px; max-height:300px;" />
                        }
                    }
                </td>

                <td>
                    <a href="/Adiministrador/Editar?id=@item.RESTAUID"><button type="button" class="btn btn-warning">Editar</button></a>
                    <a href="/Adiministrador/Excluir?id=@item.RESTAUID"><button type="button" class="btn btn-danger">Excluir</button></a>
                </td>
            </tr>
        }
    </tbody>



</table>